### ISSUE TITLE
Conversion error when missing Date Time Original in EXIF data

### ISSUE THREAD

**Issue by focher** [BenjaminBrandmeier/angular2-image-gallery#19]
When running convert.js on a folder of images, if the images do not contain the Date Time Original attribute in the EXIF profile data the script generates an error and aborts.

```
date: features['Profile-EXIF']['Date Time Original']

TypeError: Cannot read property 'Date Time Original' of undefined
```

Commenting out line 89 `date: features['Profile-EXIF']['Date Time Original']` allows the script to run and complete successfully.

Is Date Time Original required for certain functionality?

**Comment by BenjaminBrandmeier** [comment]
Thanks for raising awareness on that.
The convert.js script provides two functions to sort your images. One is by file name and one by the original date time you took the image. If you like to upload images of a coverage from a wedding or something like that. 

Unfortunately the sortByDate function is commented out hard-coded. We should allow to define the sorting mechanism via a command line parameter.

Since the collection of the data happens before the sorting process we should do something like this:
We should only collect this data if it's present. If someone tries to sort with non-existing dates we should raise a warning.

If you'd like to, you can come up with a PR on that. Otherwise I can have a look at this latest next weekend.

**Comment by BenjaminBrandmeier** [comment]
I published another minor version (0.5.5) on npm and made sure that images without EXIF information work as well.

The sorting should be configurable nevertheless. Are you willing to make a PR on this? If you don't respond by Friday I will take care of this on my own.

**Comment by BenjaminBrandmeier** [comment]
Now you are able to specify the sorting algorithm when running the pre-processing script.
-n (sort by file name, default)
-d (sort by acutal creation time of the image, EXIF)

I'm planning to make a sorting based on the primary image color in the future. 
This will be fun, let's see if it works ;-)

**Comment by BenjaminBrandmeier** [comment]
Just addding a remark here that it is now possible to sort by the primary image color with the -c flag. This can still be considered experimental though.
