### ISSUE TITLE
Changing Gallery

### ISSUE THREAD

**Issue by nevakee716** [BenjaminBrandmeier/angular2-image-gallery#27]
Hello

If I change the galleryName parameter of the component, it doesn't work correctly

**Comment by BenjaminBrandmeier** [comment]
Please be more specific.
Did you ran the pre-processing script with the corresponding gallery name before?

**Comment by stefan-frank** [comment]
I have got the same issue, I presume.

I have run the pre-processing script with a galleryName (--gName=myGallery). If I then use 

`<gallery 
    [galleryName]="myGallery" `

I receive an error in the console, that it can not access the resources - instead of "myGallery" the path is substituted with "undefined":
`http://localhost:4200/assets/img/gallery/undefined/preview_xxs/IMG_0306.JPG`

I have been looking at the gallery-component, and it looks fine to me. Repeating the pre-processing without a gallery name is working fine.

**Comment by stefan-frank** [comment]
Probably found the issue:

It may be a life cycle issue: during ngOnInit() the decorated property values haven't been propagated. Therefore the property is still "undefined". The fetchDataAndRender() method must be called later?

**Comment by stefan-frank** [comment]
The solution is outlined in #25. This issue might be closed @nevakee716 ?

**Comment by nevakee716** [comment]
It's not the same, after the component start, I want to change and display another gallery, so I change the galleryName but it's not working

**Comment by BenjaminBrandmeier** [comment]
Alright, understood.

@victooor Do you have time to look into this and provide another PR? Otherwise I will try to get some free time somewhen to fix this.

**Comment by victooor** [comment]
@BenjaminBrandmeier sure, I will look into this

**Comment by BenjaminBrandmeier** [comment]
I merged victooor's PR and will publish a new version including this shortly (0.6.1).
This should fix this issue, if not please comment here again.
